heat_template_version: 2013-05-23
description: >
  Heat tomcat template,launching a new ubuntu instance with tomcat web server application 

parameters:

  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the instance
  instance_type:
    type: string
    description: Instance type for tomcat server
    default: m1.small
  image_id:
    type: string
    description: >
      This is sample template for bluemeric
    default: 8eb30a93-5723-4a24-9fd4-01a561cef965

  net_id:
    type: string
    description: Network ID to use for the instance.
    default: public


resources:
  tomcat_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      networks:
      - network: { get_param: net_id }
      key_name: { get_param: key_name }
      user_data: { get_file: tomcat.sh }

            
outputs:
  WebsiteURL:
    description: URL for tomcat 
    value:
      str_replace:
        template: http://host:8080
        params:
          host: { get_attr: [tomcat_instance, first_address] }

