heat_template_version: 2013-05-23


#heat_template_version: 2015-10-15


description: >
  Heat WordPress template to support F20, using only Heat OpenStack-native
  resource types, and without the requirement for heat-cfntools in the image.
  WordPress is web software you can use to create a beautiful website or blog.
  This template installs a single-instance WordPress deployment using a local
  MySQL database to store the data.

parameters:

  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the instance
  instance_type:
    type: string
    description: Instance type for WordPress server
    default: m1.small
  image_id:
    type: string
    description: >
      Name or ID of the image to use for the WordPress server.
      Recommended values are fedora-20.i386 or fedora-20.x86_64;
      get them from http://cloud.fedoraproject.org/fedora-20.i386.qcow2
      or http://cloud.fedoraproject.org/fedora-20.x86_64.qcow2 .
    default: 8eb30a93-5723-4a24-9fd4-01a561cef965

  net_id:
    type: string
    description: Network ID to use for the instance.
    default: public

resources:
  wordpress_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      networks:
      - network: { get_param: net_id }
      key_name: { get_param: key_name }
      user_data: { get_file: wordpress.sh }
      # user_data_format: RAW
      # user_data:
      #   str_replace:
      #     template: { get_file: /home/bluemeric/wordpress.sh }
      #     params:
      #       $wq: {  get_param: sample }
          
#      user_data:
#        get_file: http://192.168.1.75:8080/v1/AUTH_fd87455d2df74ff080c31fa92af7d139/shellscript/wordpress.sh
            
outputs:
  WebsiteURL:
    description: URL for Wordpress wiki
    value:
      str_replace:
        template: http://host/wordpress
        params:
          host: { get_attr: [wordpress_instance, first_address] }

